dating_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, re_path
from django.contrib import admin
from profiles import urls as profile_urls
from chat import urls as chat_urls
from home import urls as home_urls
from account import urls as account_urls
from checkout import urls as subscribe_urls
from search import urls as search_urls
from django.views.static import serve
from .settings import MEDIA_ROOT


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include(home_urls)),
    re_path(r'accounts/', include(profile_urls)),
    re_path(r'chat/', include(chat_urls)),
    re_path(r'subscribe/', include(subscribe_urls)),
    re_path(r'my-account/', include(account_urls)),
    re_path(r'search/', include(search_urls)),
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})   
    ]

profiles/urls.py
from django.urls import include, re_path
from profiles.views import logout, login, register, create_profile, member_profile, delete, verification_message
from profiles import url_reset

urlpatterns = [
    re_path(r'^logout/', logout, name='logout'),
    re_path(r'^login/', login, name='login'), 
    re_path(r'^register/', register, name='register'),
    re_path(r'^create-profile/', create_profile, name='create_profile'),
    re_path(r'^delete/', delete, name="delete"),
    re_path(r'^verification-message/', verification_message, name="verification_message"),
    re_path(r'^member/(?P<id>\d+)', member_profile, name='member_profile'),
    re_path(r'^password-reset/', include(url_reset))
]

search/urls.py
from django.urls import include, re_path
from search.views import search

urlpatterns = [
    re_path(r'^$', search, name="search"),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
    
class Conversations(models.Model):
    participants = models.ManyToManyField(User, related_name="participants", unique=False)

class Messages(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender", unique=False)
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="receiver", unique=False)
    conversation = models.ForeignKey(Conversations, on_delete=models.CASCADE, related_name="conversations")
    message_content = models.TextField(max_length=500, default='', blank=False)
    created_on = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False, blank=False)
    
class Winks(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="winks_sender", unique=False)
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="winks_receiver", unique=False)
    created_on = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False, blank=False)

class Views(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="views_sender", unique=False)
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="views_receiver", unique=False)
    created_on = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False, blank=False)  

class Reject(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="rejected_sender", unique=False)
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="rejected_receiver", unique=False)
    created_on = models.DateTimeField(auto_now_add=True)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from chat.models import Conversations
from checkout.models import Subscription
from django.db.models.signals import post_save, pre_delete
from django.utils.crypto import get_random_string
from django.core.validators import MaxValueValidator, MinValueValidator
import uuid
import datetime
import os
import math
from django.db.models.expressions import RawSQL
import stripe
from django.db.backends.signals import connection_created
from django.dispatch import receiver
import os


"""
Only necessary for local and testing sqlite databases
As SQLite does not support math functions, the following function adds the
capability for it to do so
"""
if "DEVELOPMENT" in os.environ or "TESTING" in os.environ:
    @receiver(connection_created)
    def extend_sqlite(connection=None, **kwargs):
        cf = connection.connection.create_function
        cf('acos', 1, math.acos)
        cf('cos', 1, math.cos)
        cf('radians', 1, math.radians)
        cf('sin', 1, math.sin)

class LocationManager(models.Manager):
    
    # Assistance from https://stackoverflow.com/questions/19703975/django-sort-by-distance
    def nearby_locations(self, citylat, citylong, max_distance=None):
        """
        Return objects sorted by distance to specified coordinates
        which distance is less than max_distance given in kilometers
        """
        gcd_formula = "6371 * acos(cos(radians(%s)) * \
        cos(radians(citylat)) \
        * cos(radians(citylong) - radians(%s)) + \
        sin(radians(%s)) * sin(radians(citylat)))"
        distance_raw_sql = RawSQL(
            gcd_formula,
            (citylat, citylong, citylat)
        )
    
        if max_distance is not None:
            return self.annotate(distance=distance_raw_sql).filter(distance__lt=max_distance)
        else:
            return self.annotate(distance=distance_raw_sql)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, default='', blank=False)
    HAIR_COLOUR = (
        ('BLACK', 'Black'),
        ('BLONDE', 'Blonde'),
        ('BROWN', 'Brown'),
        ('RED', 'Red'),
        ('GREY', 'Grey'),
        ('BALD', 'Bald'),
        ('BLUE', 'Blue'),
        ('PINK', 'Pink'),
        ('GREEN', 'Green'),
        ('PURPLE', 'Purple'),
        ('OTHER', 'Other'),
    )
    BODY_TYPE = (
        ('THIN', 'Thin'),
        ('AVERAGE', 'Average'),
        ('FIT', 'Fit'),
        ('MUSCULAR', 'Muscular'),
        ('A LITTLE EXTRA', 'A Little Extra'),
        ('CURVY', 'Curvy'),
    )
    LOOKING_FOR = (
        ('MALE', 'Men'),
        ('FEMALE', 'Women'),
        ('BOTH', 'Both'),
    )
    APPROVAL = (
        ('TO BE APPROVED', 'To be approved'),
        ('APPROVED', 'Approved'),
        ('NOT APPROVED', 'Not approved')
    )
    
    HAIR_LENGTH = (
        ('LONG', 'Long'),
        ('SHOULDER LENGTH', 'Shoulder Length'),
        ('AVERAGE', 'Average'),
        ('SHORT', 'Short'),
        ('SHAVED', 'Shaved')
    )
    ETHNICITY = (
        ('WHITE', 'White'),
        ('ASIAN: INDIAN', 'Asian: Indian'),
        ('ASIAN: PAKISTANI', 'Asian: Pakistani'),
        ('ASIAN: BANGLADESHI', 'Asian: Bangladeshi'),
        ('ASIAN: CHINESE', 'Asian: Chinese'),
        ('BLACK', 'Black'),
        ('MIXED', 'Mixed'),
        ('OTHER ETHNICITY', 'Other Ethnicity')
    )
    RELATIONSHIP_STATUS = (
        ('NEVER MARRIED', 'Never Married'),
        ('DIVORCED', 'Divorced'),
        ('WIDOWED', 'Widowed'),
        ('SEPARATED', 'Separated')
    )
    EDUCATION = (
    ('HIGH SCHOOL', 'High School'),
    ('COLLEGE', 'College'),
    ('BACHELORS DEGREE', 'Bachelors Degree'),
    ('MASTERS', 'Masters'),
    ('PHD / POST DOCTORAL', 'PhD / Post Doctoral'),
    )
    GENDER = (
        ("MALE", "Male"),
        ("FEMALE", "Female"))

    gender = models.CharField(choices=GENDER, default="MALE", max_length=6)
    hair_length = models.CharField(choices=HAIR_LENGTH, default="LONG", blank=False, max_length=100)
    ethnicity = models.CharField(choices=ETHNICITY, default="WHITE", blank=False, max_length=100)
    relationship_status = models.CharField(choices=RELATIONSHIP_STATUS, default="NEVER MARRIED", blank=False, max_length=100)
    education = models.CharField(choices=EDUCATION, default="HIGH SCHOOL", blank=False, max_length=100)
    height = models.DecimalField(max_digits=10, default=180.34, decimal_places=2)
    hair_colour = models.CharField(choices=HAIR_COLOUR, default="BLACK", blank=False, max_length=10)
    body_type = models.CharField(choices=BODY_TYPE, default="AVERAGE", blank=False, max_length=15)
    looking_for = models.CharField(choices=LOOKING_FOR, default='BOTH', blank=False, max_length=6)
    children = models.BooleanField(default=False)
    location = models.CharField(max_length=100, default='', blank=False)
    citylat = models.DecimalField(max_digits=9, decimal_places=6, default='-2.0180319')
    citylong = models.DecimalField(max_digits=9, decimal_places=6, default='52.5525525')
    birth_date = models.DateField(null=True, default='1990-01-01', blank=True)
    is_premium = models.BooleanField(default=False)
    is_verified = models.CharField(choices=APPROVAL, default="TO BE APPROVED", blank=False, max_length=14)
    
    objects = LocationManager()
    
    # Assistance from https://stackoverflow.com/questions/5056327/define-and-insert-age-in-django-template
    def age(self):
        return int((datetime.date.today() - self.birth_date).days / 365.25  )

# Assistance from https://stackoverflow.com/questions/2673647/enforce-unique-upload-file-names-using-django
def image_filename(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('images/', filename)
    
class ProfileImage(models.Model):
    
    APPROVAL = (
        ('TO BE APPROVED', 'To be approved'),
        ('APPROVED', 'Approved'),
        ('NOT APPROVED', 'Not approved')
    )
    
    user = models.ForeignKey(User, on_delete=models.CASCADE,default=None)
    image = models.ImageField(upload_to=image_filename, blank=True)
    is_verified = models.CharField(choices=APPROVAL, default="TO BE APPROVED", blank=False, max_length=14)

    
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)
    
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_user_profile, sender=User)

def pre_delete_user(sender, instance, **kwargs):
    # Before user deleted, delete all conversations they were participants of
    conversations = Conversations.objects.filter(participants=instance.id)
    for conversation in conversations:
        conversation.delete()
    
    # Before user deleted, cancel all subscriptions
    customer = Subscription.objects.filter(user_id=instance.id).first()
    try:
        if customer:
            stripe_customer = stripe.Customer.retrieve(customer.customer_id)
            for sub in stripe_customer.subscriptions.data:
                stripe.Subscription.modify(
                    sub.id,
                    cancel_at_period_end=True
                )
    except:
        print('Pre-delete user failed')
        
pre_delete.connect(pre_delete_user, sender=User)

profiles/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError
from .models import Profile, ProfileImage
from chat.models import Messages
from dating_app import settings

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

# This will definitely work
class MyUserCreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(MyUserCreationForm, self).__init__(*args, **kwargs)

        self.fields['email'].required = True


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'maxlength':'12'}))
    password1 = forms.CharField(label="Enter Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)
    
    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        
        self.fields['email'].required = True

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
    
    class Meta:
        model = User
        fields = ['email', 'username', 'password1', 'password2']
        
    def cleaned_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if User.objects.filter(email=email).exclude(username=username):
            raise forms.ValidationError(u'Email address has been used previously. Please choose another')
    
        # Add cleaned username
    
        return email
    
    def cleaned_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        
        if not password1 or password2:
            raise ValidationError("Password fields must be filled in")
            
        if password1 != password2:
            raise ValidationError("Passwords do not match. Please try again.")
            
        return password2    
        
class EditProfileForm(UserChangeForm):
    password = None
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    # Get rid of password help text
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user',None)
        super(EditProfileForm, self).__init__(*args, **kwargs)
        
        for fieldname in ['confirm_password', 'username']:
            self.fields[fieldname].help_text = None

    def clean_confirm_password(self):
        password = self.cleaned_data['confirm_password']
        if not self.user.check_password(password):
            raise forms.ValidationError("Incorrect Password Entered")
        return password
        
    
    class Meta:
        model = User
        fields = ('email', 'username')

        
class ProfileForm(forms.ModelForm):
    
    HEIGHT_CHOICES = (
        ("152.4","5' 0"),
        ("154.94","5' 1"),
        ("157.48","5' 2"),
        ("160.02","5' 3"),
        ("162.56","5' 4"),
        ("165.1","5' 5"),
        ("167.64","5' 6"),
        ("170.18","5' 7"),
        ("172.72","5' 8"),
        ("175.26","5' 9"),
        ("177.8","5' 10"),
        ("180.34","5' 11"),
        ("182.88","6' 0"),
        ("185.42","6' 1"),
        ("187.96","6' 2"),
        ("190.5","6' 3"),
        ("193.04","6' 4"),
        ("195.58","6' 5"),
        ("198.12","6' 6"),
        ("200.66","6' 7"),
        ("203.2","6' 8"),
        ("205.74","6' 9"),
        ("208.28","6' 10"),
        ("210.82","6' 11")
    )
    
    
    CHILDREN_CHOICES = (
        (True, "Yes"),
        (False, "No")
        )
    
    location = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'id':'autocomplete'}), required=True)
    citylat = forms.CharField(widget=forms.HiddenInput, required=True)
    citylong = forms.CharField(widget=forms.HiddenInput, required=True)
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'bio-field', 'maxlength': '200'}), required=True)
    # Add custom validation, date must be over 18
    birth_date = forms.DateTimeField(input_formats=settings.DATE_INPUT_FORMATS)
    children = forms.ChoiceField(choices = CHILDREN_CHOICES, initial='', widget=forms.Select(), required=True)
    height = forms.ChoiceField(choices = HEIGHT_CHOICES, initial='', widget=forms.Select(), required=True)
    
    class Meta:
        model = Profile
        fields = ( 'bio', 'gender', 'hair_colour', 'hair_length', 'body_type', 'ethnicity', 'relationship_status', 'looking_for', 'education', 'height', 'children', 'location',  'citylat', 'citylong', 'birth_date')
        widgets = {
            'date' : forms.DateInput(attrs={'type':'date'})
        }    
    
class ProfileImageForm(forms.ModelForm):
    
    image = forms.ImageField(label='', required=False, error_messages = {'invalid':"Image files only"}, widget=forms.FileInput(attrs = {'class': "profile-photo-input"}))

    class Meta:
        model = ProfileImage
        fields = ('image', )
        
class MessagesForm(forms.ModelForm):
    # message_content = forms.CharField(widget=forms.TextInput)
    
    class Meta:
        model = Messages
        fields = ('message_content', )

profiles/templates/create-profile.html
{% extends 'base.html' %} {% block page_title %}Update your Profile{% endblock %} {% load static from static %} 
<!--CSS for datepicker-->
{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
{% endblock %} 

{% block content %}
<!--Profile details form-->
<section class="profile-card-container">
    <div class="card-container card-margin-top">
        <div class="card-form card">
            <div class="card-form-container">
                <h3>Profile Details</h3>
                <hr>
                <p class="card-form-subtitle">Customise your public profile</p>
                <p class="card-form-description">This is your opportunity to let your personality shine. A well crafted profile can increase your engagement 4x so try to make it an honest expression of who you are!</p>
                <form class="create-profile-form standard-form" method="POST" enctype="multipart/form-data">
                    {% csrf_token %} {{ profile_form }}
                    <!--Profile photos form-->
                    <label>Profile Photos: </label> {{ formset.management_form }}
                    <div class="profile-form-container">
                        {% for form in formset %}
                        <div id="field_{{form.id.id_for_label}}" class="profile-photo-container">

                            <div {% if not form.initial.image %}style="display: none;" {% endif %} class="profile-delete-icon-container">
                                <i onclick="delete_profile_photo( event, 'field_{{form.id.id_for_label}}' )" class="far fa-trash-alt"></i>
                            </div>
                            {{form}}
                            <div class="profile-photo-overlay">
                                <div class="profile-icon-container-absolute">
                                    <div class="profile-icon-container-flex">
                                        <i class="fas fa-plus"></i>
                                    </div>
                                </div>
                                {% if form.initial.image %}
                                <div class="profile-photo-image" style="background-image: url({{form.initial.image.url}})"></div>
                                {% else %}
                                <div class="profile-photo-image" style="background-image: none"></div>
                                {% endif %}
                            </div>

                            {% for hidden in form %} {% if not 'image' in hidden.auto_id %}
                            <input hidden class="delete-hidden-input" type="checkbox" name="delete" value="{{ hidden.value }}"> {% endif %} {% endfor %}

                        </div>
                        {% endfor %}
                    </div>
                    <div class="standard-form-submit">
                        <input type="submit" value="UPDATE" class="submit-wide submit-success" name="message_submit">
                        <img class="loading-image" src="{% static 'temp/34-1.gif' %}"></img>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %} {% block js %}
<script>
    // Using Google Places API, display autocomplete options for location
    // Assistance from Google Maps API documentation
    var placeSearch, autocomplete;
    function initAutocomplete() {
        autocomplete = new google.maps.places.Autocomplete(
            (document.getElementById('autocomplete')), { types: ['geocode'] })  
        google.maps.event.addListener(autocomplete, 'place_changed', function() {
            var place = autocomplete.getPlace();
            // Update hidden fields with selected location and coordinates
            document.getElementById('autocomplete').value = place.name;
            document.getElementById('id_citylat').value = place.geometry.location.lat().toFixed(6);
            document.getElementById('id_citylong').value = place.geometry.location.lng().toFixed(6);
        })  
    }
</script>
<!--Google maps and datepicker dependencies-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC8CKdpcMMIDq0BZ7x7DMbH_71XpVH4HWo&libraries=places&callback=initAutocomplete" async defer></script>

{% endblock %}

profiles/templates/login.html
{% extends 'base_preregister.html' %} {% block page_title %}Login{% endblock %} {% block content %}


<!--Login form-->
<section class="profile-card-container">
    <div class="card-container card-margin-top">
        <div class="card-form card account-access-form">
            <div class="card-form-container">
                <h3>Login to Your Account</h3>
                <hr>
                <form class="standard-form" method="POST">
                    {% csrf_token %} {{ login_form }}
                    <button class="submit-wide submit-success" type="submit">Register</button>
                </form>


            </div>
            <p class="forgot-password">Forgot password? Reset it <a href="{% url 'password_reset' %}">here</a></p>

        </div>
    </div>
</section>

<div class="footer-spacer">
</div>

{% endblock %}

profiles/templates/member.html
{% extends 'base.html' %} {% block page_title %}{{member.username}}'s Profile{% endblock %} {% load static from static %} {% block content %}
<!--Profile images-->
<div class="profile-img-container">
    <div class="icon-wink-form-container {% if current_user %}disabled-wink-container{% endif %}">
        <button id="wink-receiver-input" {% if not current_user %}onclick="send_wink_grid_link({{ member.id }})" {% endif %}><i class="far fa-smile-wink"></i></button>
    </div>
    <!--Edit profile button-->
    {% if request.user.id == member.id %}
    <div class="icon-edit-container">
        <form action="{% url 'create_profile' %}">
            <button><i class="far fa-edit"></i></button>
        </form>
    </div>
    {% endif %}
    <!--Profile images-->
    <div class="profile-img-draggable">
        {% for image in member.profileimage_set.all %}
        <!--Displays profile image or placeholder if image is not verified-->
        {% if image.is_verified == "APPROVED" or request.user.id == member.id %}
        <img class="profile-img" src="{{image.image.url}}"> {% else %}
        <img class="profile-img" src="{% static 'temp/profile-placeholder.png' %}"> {% endif %} {% endfor %}
    </div>
</div>

<section class="profile-card-container container">
    <div class="row">
        <div class="col-sm-12 profile-username">
            <h2>{{member.username}}</h2>
            <h3>{{member.profile.age}}</h3>
        </div>
        <div class="col-sm-12 col-md-7">
            <!--Member bio-->
            <div class="card-container">
                <div class="card">
                    <p>{% if member.profile.is_verified == "APPROVED" %}{{member.profile.bio}}{% else %}Our verification team is currently vetting this member. This user's profile will be visible soon.{%endif%}</p>
                </div>
            </div>
            {% if member.profile.is_verified == "APPROVED" %}
            <div class="card-container">
                <div class="card">
                    <!--Member details-->
                    <table class="standard-table">
                        <tr>
                            <td>Location:</td>
                            <td class="standard-table-feature">{{member.profile.location}}</td>
                        </tr>
                        <tr>
                            <td>Gender:</td>
                            <td class="standard-table-feature">{{member.profile.gender|title}}</td>
                        </tr>
                        <tr>
                            <td>Hair Length:</td>
                            <td class="standard-table-feature">{{member.profile.hair_length|title}}</td>
                        </tr>
                        <tr>
                            <td>Hair Color:</td>
                            <td class="standard-table-feature">{{member.profile.hair_colour|title}}</td>
                        </tr>
                        <tr>
                            <td>Ethnicity:</td>
                            <td class="standard-table-feature">{{member.profile.ethnicity|title}}</td>
                        </tr>
                        <tr>
                            <td>Relationship Status:</td>
                            <td class="standard-table-feature">{{member.profile.relationship_status|title}}</td>
                        </tr>
                        <tr>
                            <td>Education:</td>
                            <td class="standard-table-feature">{{member.profile.education|title}}</td>
                        </tr>
                        <tr>
                            <td>Height:</td>
                            <td class="standard-table-feature">{{height}}</td>
                        </tr>
                        <tr>
                            <td>Body Type:</td>
                            <td class="standard-table-feature">{{member.profile.body_type|title}}</td>
                        </tr>
                        <tr>
                            <td>Children:</td>
                            <td class="standard-table-feature">{% if member.profile.children %}Yes{%else%}No{%endif%}</td>
                        </tr>
                        <tr>
                            <td>Looking For:</td>
                            <td class="standard-table-feature">{%if member.profile.looking_for == "BOTH" %}Men & Women{% else %}{{member.profile.looking_for|title}}{% endif %}</td>
                        </tr>
                    </table>
                </div>
            </div>
            {%endif%}
        </div>
        <div class="col-sm-12 col-md-5">
            <!--Send message form-->
            <div class="card-container">
                <div class="{% if current_user %}disabled-card{%endif%} card-form card">
                    <div class="card-form-container">
                        <h3>Message {{member.username}}</h3>
                        <hr>
                        <form class="standard-form" method="POST">
                            {% csrf_token %} {% if current_user %}
                            <label for="id_message_content">Message content:</label>
                            <textarea disabled="" cols="40" rows="10" id="id_message_content" maxlength="500"></textarea>
                            <input type="submit" disabled value="SEND" class="disabled-button submit-wide submit-success" name="message_submit" /> {% else %} {{ message_form }}
                            <input type="submit" value="SEND" class="submit-wide submit-success" name="message_submit" /> {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %} {% block js %}
<!--Necessary for draggable elements-->
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>

{% endblock %}

profiles/templates/register.html
{% extends 'base_preregister.html' %} {% block page_title %}Register{% endblock %} {% block content %}
<!--Register form-->
<section class="profile-card-container">
  <div class="card-container card-margin-top">
    <div class="card-form card account-access-form">
      <div class="card-form-container">
        <h3>Register an Account</h3>
        <hr>
        <form class="standard-form" method="POST">
          {% csrf_token %} 
          {{registration_form}}
          <button class="submit-wide submit-success" type="submit">Register</button>
        </form>


      </div>
    </div>
  </div>
</section>

<div class="footer-spacer">
</div>

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
{% endblock %}

profiles/templates/verification-message.html
{% extends 'base.html' %} {% block page_title %}Verification Message{% endblock %}{% block content %}


<!--Verification information card-->
<section class="profile-card-container">
    <div class="card-container card-margin-top">
        <div class="card-form card">
            <div class="card-form-container">
                <h3>Verification</h3>
                <hr>
                <p>To ensure our martimony community is safe and fun for all, every profile is manually verified by our verification team.
                    <br><br> Please bear with us while we approve your profile. During this time, you will still be able to use the site, however some features may be limited.
                    <br><br> Average approval time is 20 minutes<br><br></p>

                <a class="btn standard-button" href="{% url 'index' %}">START Wedding Process</a>


            </div>

        </div>
    </div>
</section>

{% endblock %}